# A SourceHut build manifest. See https://man.sr.ht/builds.sr.ht/manifest.md
# for more information.
#
image: archlinux
packages:
  - libevdev
  - libinput
  - libxkbcommon
  - libxml2
  - meson
  - wayland
  - wayland-protocols
  - wlroots
  - xorg-server-xwayland
sources:
  - https://github.com/wizbright/waybox
tasks:
  - setup: |
      cd waybox
      meson setup build
  - build: |
      cd waybox
      ninja -C build
