image: archlinux
packages:
    # Packages needed by Waybox
  - meson
  - wayland
  - wayland-protocols
  - libxkbcommon
  - libxml2
    # Packages needed for wlroots
  - mesa
  - xorg-server-xwayland
  - xcb-util-image
  - libinput
  - libdrm
  - udev
  - pixman
  - seatd
sources:
  - https://github.com/wizbright/waybox
  - https://gitlab.freedesktop.org/wlroots/wlroots
tasks:
  - wlroots: |
      cd wlroots
      meson --prefix=/usr build
      ninja -C build
      sudo ninja -C build install
  - setup: |
      cd waybox
      meson build
  - build: |
      cd waybox
      ninja -C build
